# Site settings
title: overconstrained
email: hfossli@gmail.com
description: "Information about Cassowary, its community and different implementations."
skills: Cassowary projects and its community.
fork-me-link: https://github.com/hfossli/Overconstrained

project-platforms:
  - title: C++
    slug: cplusplus
  - title: Web
    slug: web
  - title: Haxe
    slug: haxe
  - title: C
    slug: c
  - title: Java
    slug: java
  - title: Python
    slug: python
  - title: Objective-C
    slug: objectivec
  - title: Smalltalk
    slug: smalltalk

# Color settings (hex-codes without the leading hash-tag)
colors:
  navbar:
    main: 1a242f
    subtle: 000000
    contrast: ffffff
    callout: 000000
    link: d8a416
    link-focus: d8a416
    link-focus-background: ffffff
  footer:
    main: 1a242f
    subtle: 000000
    contrast: ffffff
    callout: 000000
    link: d8a416
    link-focus: d8a416
    link-focus-background: ffffff
  primary:
    main: 233140
    subtle: 233140
    contrast: ffffff
    callout: 1d445c
    link: d8a416
    link-focus: d8a416
  secondary:
    main: 233140
    subtle: 628c9c
    contrast: ffffff
    callout: 6bdc48
    link: d8a416
    link-focus: d8a416
  tertiary:
    main: e4e4e4
    subtle: aaa
    contrast: 3d403e
    callout: 6bdc48
    link: d8a416
    link-focus: d8a416
  quaternary:
    main: 1d445c
    subtle: 00b6ff
    contrast: ffffff
    callout: 6bdc48
    link: d8a416
    link-focus: d8a416

# Build settings
markdown: kramdown
permalink: pretty
